version: '3.5' # 或者使用你适用的Compose版本

services:
  kbrain:
    container_name: rag-demo
    image: python:3.10
    user: "root"  # 以root用户运行容器
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           device_ids: ["0"]

    restart: always
    network_mode: host
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./:/opt/rag-demo
      # - ./gst-nvinfer-custom:/opt/nvidia/deepstream/deepstream/sources/video_analysis_platform/gst-nvinfer-custom
    working_dir: /opt/rag-demo
    # command: ["bash", "/opt/nvidia/deepstream/deepstream/sources/video_analysis_platform/autoScript/kbrain_auto_start.sh"]
    # for debug only
    stdin_open: true
    tty: true
